[project]
name = "sensory-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "igor crissaff", email = "igorcrissaff06@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "faster-whisper>=1.2.1",
    "matplotlib>=3.11.2",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
]

[project.scripts]
sensory-cli = "sensory_cli:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
